apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdtd
spec:
  template:
    spec:
      containers:
        - name: sdtd      
          env:
            - name: PUID
              value: 0
            - name: GUID
              value: 0